Fix for overlapping targets and constraints
InferenceQL/inferenceql.inference pull request #19
Opened 2022-09-22 22:03 UTC by LarryLegend33

## Overview 
* Change logpdf and simulate for the XCat record to enable overlapping targets and constraints. 
* Update test suite to test for these changes. 
## Motivation
* Resolves #17

2022-09-23 18:12 UTC, Schaechtle requested changes
I've left an inline comment about removing stuff from the constraints -- but not the target.

2022-09-27 17:10 UTC, LarryLegend33 commented on src/inferenceql/inference/gpm/crosscat.cljc
> +          unconstrained_targets (filterv (fn[x] (not (some #(= x %) intersection))) (set targets))]
Hey zane this is really helpful. I didn't realize sets could be applied as functions. I think you're right that my anonymous function is a bit opaque. I'd suggest that the right replacement for (filterv (fn[x] (not (some #(= x %) intersection))) (set targets)))  in this case is actually (remove intersection (set targets)) then, right? That way you'd be left with only the targets that aren't in intersection. To get the exact same result I would add a vec call to the beginning.

2022-10-11 18:24 UTC, LarryLegend33 commented on src/inferenceql/inference/gpm/crosscat.cljc
> +                                                       (apply (partial dissoc constraints) intersection))]
Yeah you're right I thought I needed this to partially apply dissoc to just targets and then apply that to each individual arg of intersection, but dissoc takes multiple keys at once.

2022-10-11 18:25 UTC, LarryLegend33 commented on src/inferenceql/inference/gpm/crosscat.cljc
> +             (apply merge (select-keys constraints intersection)))))
Nope -- thanks!

2022-10-11 18:26 UTC, LarryLegend33 commented on src/inferenceql/inference/gpm/crosscat.cljc
> +                  (= (shared_key targets) (shared_key constraints))))
I like it -- definitely clearer intent to compare the values in targets and constraints from the keys in intersection

2022-10-11 18:34 UTC, LarryLegend33 commented on src/inferenceql/inference/gpm/crosscat.cljc
> +                                                       (apply (partial dissoc constraints) intersection))]
totally right

2022-10-18 19:24 UTC, Schaechtle approved these changes
thanks @LarryLegend33!

2022-10-18 19:24 UTC, merged